package com.omarkarimli.cora.ui.presentation.common.state

object SuccessType {
    const val CONTINUE = "Continue"
    const val LOG_IN = "Logged in"
    const val SIGN_IN = "Signed in"
    const val SIGN_UP = "Signed up"
    const val SIGN_OUT = "Signed out"
    const val GET_USER = "Got user"
    const val GET_ABOUT = "Got about"
    const val UPDATE_PROFILE = "Updated profile"
    const val SELECT_SUBSCRIPTION = "Selected subscription"
    const val SET_SUBSCRIPTIONS = "Set subscriptions"
    const val GET_SUBSCRIPTIONS = "Got subscriptions"
    const val GET_GUIDELINES = "Got guidelines"
    const val SET_GUIDELINES = "Set guidelines"
    const val GET_JOURNALS = "Got journals"
    const val SET_JOURNALS = "Set journals"
    const val SET_ABOUT = "Set about"
    const val SETTINGS_UPDATE = "Settings updated"
    const val REPORT_SEND = "Report sent"
    const val IMAGE_ANALYSIS = "Image analysed"
    const val CATEGORY_RESULT = "Category result found"
    const val GET_CATEGORIES = "Got categories"
    const val SET_CATEGORIES = "Set categories"
    const val MESSAGE_SEND = "Message sent"
    const val DOWNLOAD_COMPLETE = "Download completed"
}